# Generated by Django 2.1.3 on 2018-12-04 03:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user_id',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default=django.utils.timezone.now, error_messages={'required': 'Add a body for your article.'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 12, 4, 3, 36, 42, 694380, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 12, 4, 3, 36, 42, 694430, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(error_messages={'required': 'Add a description for your article.'}),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(error_messages={'required': 'Add a title for your article.'}, max_length=255),
        ),
    ]
