# Generated by Django 2.1.3 on 2018-12-05 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181204_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 12, 5, 9, 31, 3, 299459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 12, 5, 9, 31, 3, 299493, tzinfo=utc)),
        ),
    ]
